# Generated by Django 6.0.8 on 2026-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0002_rename_creator_marketplaceoffer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplaceoffer',
            options={'ordering': ['-updated_at'], 'verbose_name': 'marketplace offer', 'verbose_name_plural': 'marketplace offers'},
        ),
        migrations.AlterModelOptions(
            name='offerpackage',
            options={'ordering': ['offer', 'price'], 'verbose_name': 'offer package', 'verbose_name_plural': 'offer packages'},
        ),
    ]
