# Generated by Django 6.0.8 on 2026-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_create_demo_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coderruser',
            options={'ordering': ['username'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
