# Generated by Django 6.0.8 on 2026-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_location_alter_profile_tel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
