# Generated by Django 6.0.8 on 2026-08-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-updated_at'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
